name: Email Check

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  email_check_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用Node.js 20版本

    - name: Set up Python
      uses: actions/setup-python@v3  # 使用Node.js 20版本
      with:
        python-version: '3.11.7'  # 设置所需的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run email_check script
      run: python email_check.py
